package ru.alexandrorlov.weather.config

object DataLocalConfig {
    const val DATABASE_NAME = "meals.db"

    object Meal {
        const val TABLE_NAME = "Meals"
        const val COLUMN_ID = "id"
        const val COLUMN_TITLE = "title"
        const val COLUMN_DRINK_ALTERNATIVE = "drink_alternate"
        const val COLUMN_CATEGORY = "category"
        const val COLUMN_AREA = "area"
        const val COLUMN_DESCRIPTION = "description"
        const val COLUMN_URL_THUMB = "url_thumb"
        const val COLUMN_TAGS = "tags"
        const val COLUMN_URL_YOUTUBE = "url_youtube"
        const val COLUMN_INGREDIENT1 = "ingredient1"
        const val COLUMN_INGREDIENT2 = "ingredient2"
        const val COLUMN_INGREDIENT3 = "ingredient3"
        const val COLUMN_INGREDIENT4 = "ingredient4"
        const val COLUMN_INGREDIENT5 = "ingredient5"
        const val COLUMN_INGREDIENT6 = "ingredient6"
        const val COLUMN_INGREDIENT7 = "ingredient7"
        const val COLUMN_INGREDIENT8 = "ingredient8"
        const val COLUMN_INGREDIENT9 = "ingredient9"
        const val COLUMN_INGREDIENT10 = "ingredient10"
        const val COLUMN_INGREDIENT11 = "ingredient11"
        const val COLUMN_INGREDIENT12 = "ingredient12"
        const val COLUMN_INGREDIENT13 = "ingredient13"
        const val COLUMN_INGREDIENT14 = "ingredient14"
        const val COLUMN_INGREDIENT15 = "ingredient15"
        const val COLUMN_INGREDIENT16 = "ingredient16"
        const val COLUMN_INGREDIENT17 = "ingredient17"
        const val COLUMN_INGREDIENT18 = "ingredient18"
        const val COLUMN_INGREDIENT19 = "ingredient19"
        const val COLUMN_INGREDIENT20 = "ingredient20"
        const val COLUMN_MEASURE1 = "measure1"
        const val COLUMN_MEASURE2 = "measure2"
        const val COLUMN_MEASURE3 = "measure3"
        const val COLUMN_MEASURE4 = "measure4"
        const val COLUMN_MEASURE5 = "measure5"
        const val COLUMN_MEASURE6 = "measure6"
        const val COLUMN_MEASURE7 = "measure7"
        const val COLUMN_MEASURE8 = "measure8"
        const val COLUMN_MEASURE9 = "measure9"
        const val COLUMN_MEASURE10 = "measure10"
        const val COLUMN_MEASURE11 = "measure11"
        const val COLUMN_MEASURE12 = "measure12"
        const val COLUMN_MEASURE13 = "measure13"
        const val COLUMN_MEASURE14 = "measure14"
        const val COLUMN_MEASURE15 = "measure15"
        const val COLUMN_MEASURE16 = "measure16"
        const val COLUMN_MEASURE17 = "measure17"
        const val COLUMN_MEASURE18 = "measure18"
        const val COLUMN_MEASURE19 = "measure19"
        const val COLUMN_MEASURE20 = "measure20"
        const val COLUMN_SOURCE = "source"
        const val COLUMN_IMAGE_SOURCE = "imageSource"
        const val COLUMN_CREATIVE_COMMONS_CONFIRMED = "creativeCommonsConfirmed"
        const val COLUMN_DATE_MODIFIED = "dateModified"
    }
}